### ISSUE TITLE
UnicodeDecodeError：'gb2312' codec can't decode

### ISSUE THREAD

**Issue by cogitoxin** [JeziL/caj2pdf#1]
Thanks for developing this. But I got an error while running caj2pdf outlines XXX.caj -o XXX.pdf

Traceback (most recent call last):
  File "caj2pdf", line 40, in <module>
    toc = caj.get_toc()
  File "/Users/cogito/Documents/Mac/caj2pdf-master/parser.py", line 46, in get_toc
    title = toc_bytes[0].replace(b'\x00', b'').decode("gb2312").encode("utf-8")
UnicodeDecodeError: 'gb2312' codec can't decode byte 0x89 in position 18: illegal multibyte sequence

Please help.

**Comment by JeziL** [comment]
can you  provide your caj file

**Comment by cogitoxin** [comment]
不好意思回晚了，是这个：http://cdmd.cnki.com.cn/Article/CDMD-10055-1015528939.htm

**Comment by JeziL** [comment]
@cogitoxin The problem was caused by the character `塚` which is not included in GB2312 character set. Using GBK or GB18030 should fix this, try the latest commit. Thanks for the feedback. 

Interesting article by the way...
