### ISSUE TITLE
在windows下不能使用么，一直报错。

### ISSUE THREAD

**Issue by slimshaco** [JeziL/caj2pdf#13]
![image](https://user-images.githubusercontent.com/22498569/39861086-137e89a2-5472-11e8-83ea-0e6e3a0ae54d.png

**Comment by JeziL** [comment]
[异常输出（IMPORTANT!!!）](https://github.com/JeziL/caj2pdf#%E5%BC%82%E5%B8%B8%E8%BE%93%E5%87%BAimportant)
