### ISSUE TITLE
转换之后的文档出现乱码

### ISSUE THREAD

**Issue by lelandyang** [JeziL/caj2pdf#20]
附件中的CAJ文件能够成功转换，但是转换之后的文件为乱码，汉字无法正常显示。
猜想原因：所选择的字体没有嵌入到PDF文件中。
这种情况在我之前上百个CAJ逆向研究样本中出现过好几次。

附件中的压缩包包括了CAJ文件和使用CAJ2PDF转换之后的PDF文件。
[Unknown.zip](https://github.com/JeziL/caj2pdf/files/2238525/Unknown.zip)

**Comment by JeziL** [comment]
附件中的 CAJ 文件用知网的软件 [CAJCloudViewer for Mac 1.1.2(19)] 打开也提示文件损坏，除封面外都是空白页：

> 文件部分页面，无法得到原始页面大小，说明文件有损坏。
请删除，重新下载！

去知网找到了这篇文献（[链接](http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CMFD&dbname=CMFD2011&filename=1011164749.nh)），下载下来的 CAJ 文件是可以成功转换的。
