### ISSUE TITLE
目前CAJ文件包含四种格式：CAJ，HN，%PDF，KDH

### ISSUE THREAD

**Issue by zhangsunny** [JeziL/caj2pdf#21]
%PDF最好解决，直接重命名就好了，一般多是期刊论文

![default](https://user-images.githubusercontent.com/15084484/44398031-f6c9a680-a574-11e8-8b06-ff8140e2ebc6.png)

附HN和KDH格式的样本文件供作者大大参考

[HN和KDH.zip](https://github.com/JeziL/caj2pdf/files/2305985/HN.KDH.zip)

**Comment by JeziL** [comment]
感谢～

**Comment by Lotayou** [comment]
@zhangsunny 您好，能详细说下%PDF格式的文件该如何处理吗，谢谢

**Comment by zhangsunny** [comment]
%pdf格式直接手动把后缀名caj改成pdf就可以了。。
我现在发现海外版知网http://oversea.cnki.net/new/可以直接下载pdf的硕博论文，不用再转格式了

**Comment by HinTak** [comment]
These now convert well; here are the results:

[实时网络流量异常检测算法研究和系统实现_林尚朕.pdf](https://github.com/caj2pdf/caj2pdf/files/5788348/_.pdf)
[时间序列模型在卫星异常检测中的应用研究_余文艳.pdf](https://github.com/caj2pdf/caj2pdf/files/5788350/_.pdf)

remaining issues are tracked in #57 .
