### ISSUE TITLE
另外一种获得PDF格式文档的方法

### ISSUE THREAD

**Issue by Zhao-Hui-Huang** [JeziL/caj2pdf#27]
[http://eng.oversea.cnki.net/](http://eng.oversea.cnki.net/)

**在知网的海外版上，大部分文件可以以PDF的格式下载。**

**Comment by jiqing112** [comment]
tmd，知网这么贱的嘛

**Comment by jiqing112** [comment]
还真是，哎哟，还有什么好说的呢
![_2018-12-12t11-54-23 330z](https://user-images.githubusercontent.com/17674011/49868231-c2da0000-fe47-11e8-8b08-221b47f9ed0b.png)

**Comment by Umbrellazc** [comment]
感谢，真的可行。

**Comment by hqyyqh** [comment]
知网好贱。

**Comment by JeziL** [comment]
issue 的 comment 也默认会推送给所有参与讨论的人，请尽量不要发表无意义的评论。

**Comment by wanglijin** [comment]
在家没连校园网该如何使用知网海外版呢
