### ISSUE TITLE
Error on PDF objects numbering.

### ISSUE THREAD

**Issue by Hypothesis-Z** [JeziL/caj2pdf#30]
`D:\Documents\本科毕业设计\caj2pdf-master>python caj2pdf show C:\\users\\zzq\\downloads\\Lambertian.caj
File: C:\\users\\zzq\\downloads\\Lambertian.caj
Type: CAJ
Page count: 141
Outlines count: 31

D:\Documents\本科毕业设计\caj2pdf-master>python caj2pdf convert C:\\users\\zzq\\downloads\\Lambertian.caj -o C:\\users\\zzq\\downloads\\Lambertian.pdf
Error on PDF objects numbering.`

[Lambertian.zip](https://github.com/JeziL/caj2pdf/files/2952203/Lambertian.zip)

**Comment by JeziL** [comment]
添加 PDF 对象时为防止与已有的对象编号冲突，之前采取的办法是遍历 1~9999，寻找第一个未被使用的编号，这个样本这 9999 个编号真的都被占用了……

也没什么更好的办法……commit [4aed47b](https://github.com/JeziL/caj2pdf/commit/4aed47be374d8aa187e90c7bd69eada401f8718d) 改成从 99999 倒数查找未占用编号了。
