### ISSUE TITLE
文档转换不了

### ISSUE THREAD

**Issue by tao96** [JeziL/caj2pdf#31]
Traceback (most recent call last):
  File "main.py", line 58, in convert_caj
  File "cajparser.py", line 68, in convert
  File "cajparser.py", line 234, in _convert_hn
Exception: Unsupported file type.
[旋转超声辅助微细电火花加工机床研制及实验研究_张振.zip](https://github.com/JeziL/caj2pdf/files/3117205/_.zip)

**Comment by HinTak** [comment]
sample for https://github.com/JeziL/caj2pdf/issues/43

**Comment by HinTak** [comment]
This now converts well - here is the result:
[旋转超声辅助微细电火花加工机床研制及实验研究_张振.pdf](https://github.com/caj2pdf/caj2pdf/files/5788428/_.pdf)

Remaining problems are tracked in #57 .
