### ISSUE TITLE
求一个更为详细的说明

### ISSUE THREAD

**Issue by xu-kai-xu** [JeziL/caj2pdf#35]

**Comment by xu-kai-xu** [comment]
原本的说明看不懂，那些命令是在cmd里敲的吗。
求一个更加详细的说明。

**Comment by JeziL** [comment]
1. 安装 Python
2. 安装依赖 `pip install PyPDF2`
3. 下载 MuPDF，将 mutool 文件放在当前目录
4. 在命令行里运行命令

**Comment by xu-kai-xu** [comment]
谢谢啦

**Comment by xu-kai-xu** [comment]
您好 我下载好了 mupdf， 当前目录是pypdf2的安装目录还是随便自己新建一个都可以。在命令行里敲入命令后，提示`caj2pdf不是内部或外部命令`，所以还是没有弄好。麻烦您啦

**Comment by JeziL** [comment]
caj2pdf 所在的目录，命令行也需在这个目录下
如果是 Windows 原本的命令前需要加 python：`python caj2pdf ...`

**Comment by xu-kai-xu** [comment]
超感谢，弄好了，转换干净利落。

**Comment by YanB25** [comment]
在这里分享一下mac端的mutool的配置方法。

MuPDF官网的 git://git.ghostscript.com/mupdf.git 我没有办法clone下来（可能由于某些网络问题）
我点击官网右上角的download下载源码并解压
解压完毕后，使用 make -j 进行编译，在build/ 目录下会产生mutool可执行文件
将mutool的目录加入到路径当中（即确保命令行中直接输入mutool能直接运行）

**Comment by zhuqixiao** [comment]
您好，我下载mutool的时候发现了有windows版本以及tar.gz结尾的压缩版本，mutool.exe在命令行可以使用，在linux里面也可以使用吗，对于设置变量我还不是很懂。

**Comment by YanB25** [comment]
@zhuqixiao .exe结尾的文件是windows下的可执行文件，在Linux下当然无法使用。

**Comment by zhuqixiao** [comment]
请问这个怎么在linux里面运行啊...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BensonYan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 下午2:24
收件人:&nbsp;"JeziL/caj2pdf"<caj2pdf@noreply.github.com&gt;;
抄送:&nbsp;"朱骐虓"<756104916@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JeziL/caj2pdf] 求一个更为详细的说明 (#35)




@zhuqixiao .exe结尾的文件是windows下的可执行文件，在Linux下当然无法使用。

**Comment by YanB25** [comment]
@zhuqixiao 
在官网下载**源码**并解压。例如下载`mupdf-1.16.1-source.tar.gz`，名字包含`source`，意味着它是源码。

下载完成后解压。可以使用
```
$ tar xzf mupdf-1.16.1-source.tar.gz
```
进行解压。
解压完毕后使用`make -j`进行编译。

可执行文件在build/ 目录下，将该目录（的绝对路径）加入到系统路径当中。
参照[https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path](这个链接)来将目录加入到系统路径。
