### ISSUE TITLE
一个转换不了的文件

### ISSUE THREAD

**Issue by qinyongqiang** [JeziL/caj2pdf#36]
[Unsupported file type.caj.zip](https://github.com/JeziL/caj2pdf/files/3380074/Unsupported.file.type.caj.zip)

系统：MacOS 10.14.5
mupdf 版本：1.15.0
命令： ./caj2pdf convert xx.caj -o xxx.pdf
输出：Unsupported file type.

**Comment by lelandyang** [comment]
你提供的样本是NH文件，本项目的说明中已经明确提及不支持此类文件，也没有考虑支持。
@JeziL 建议在检测到NH的时候直接指明“不支持NH格式，除非有人分析出NH格式Spec”

**Comment by HinTak** [comment]
sample for #43

**Comment by HinTak** [comment]
This now converts well enough - here is the result:
[Unsupported file type.pdf](https://github.com/caj2pdf/caj2pdf/files/5788487/Unsupported.file.type.pdf)

Remaining issues are tracked in #57
