### ISSUE TITLE
一种加了DRM的PDF格式

### ISSUE THREAD

**Issue by yichinzhu** [JeziL/caj2pdf#37]
格式是PDF，但是加了DRM版权保护，cajviewer能打开，有有效期限制，盲猜需要从服务端请求某个密钥然后解密
[数论与密码.pdf](https://github.com/JeziL/caj2pdf/files/3601317/default.pdf)

**Comment by JeziL** [comment]
文件 EOF 标记后有一段 xml 格式的 DRM 相关信息。解密时的网络请求为：

向 `http://159.226.29.160/DRMMngr/auth.aspx?pn=scienceReading` POST 请求：
```xml
<?xml version="1.0" encoding="UTF-8"?>
<auth-req>
    <file-id>1909117af231c4b45218ac7e0646b740</file-id>
    <doi/>
</auth-req>
```
返回：
```xml
<?xml version='1.0' encoding='utf-8'?>
<auth>
    <password>852661a149bc473f968d1ae0593b6559</password>
</auth>
```

具体加解密算法不知道。
