### ISSUE TITLE
一个无法转换的例子

### ISSUE THREAD

**Issue by spiderman930706** [JeziL/caj2pdf#48]
[caj文件.zip](https://github.com/JeziL/caj2pdf/files/4811587/caj.zip)

**Comment by spiderman930706** [comment]
可以正常输出结果文件，但是文件不能正常打开。

**Comment by dennischancs** [comment]
我都打得开唉，你的pdf软件有问题？

**Comment by lelandyang** [comment]
@dennischancs 你是用的什么软件打开的？

**Comment by spiderman930706** [comment]
> 我都打得开唉，你的pdf软件有问题？

难受，我用的adobe acrobat reader打不开，经过你们提醒我用谷歌浏览器可以正常打开了，谢谢

**Comment by spiderman930706** [comment]
> @dennischancs 你是用的什么软件打开的？

我现在用谷歌浏览器可以正常打开了，用Adobe 的软件打不开
