### ISSUE TITLE
是否可以将caj的页面存储为图像？

### ISSUE THREAD

**Issue by leyiwang** [JeziL/caj2pdf#52]
请问是否可能可以实现将caj的页面内容通过程序读取后存储为图片？

**Comment by lelandyang** [comment]
可以。可惜你不是产品经理，烦请自己实现。
Github的issue是提bug谈技术的地方，不是用于提需求的。

**Comment by jiqing112** [comment]
有很多订阅这个项目，你这样无谓的提需求会浪费到我们的时间
