### ISSUE TITLE
Unsupported file type.

### ISSUE THREAD

**Issue by ringsaturn** [JeziL/caj2pdf#7]
尝试如下命令

```python3
python3 caj2pdf.py convert a.caj -o output.pdf
```

报错为 `Unsupported file type.`

附件如下

[a.caj.zip](https://github.com/JeziL/caj2pdf/files/1800256/a.caj.zip)

**Comment by JeziL** [comment]
这文件链接是什么鬼

**Comment by HinTak** [comment]
It is a HN file, which my new code can somewhat understand.

**Comment by HinTak** [comment]
sample for https://github.com/JeziL/caj2pdf/issues/43

**Comment by HinTak** [comment]
This now works well enough - here is the converted result:
[a.pdf](https://github.com/caj2pdf/caj2pdf/files/5788314/a.pdf)

Remaining problems with conversion are tracked in #57 .
